### ISSUE TITLE
Define terminology of SD-JWT-VC, etc.

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-terbu-sd-jwt-vc#10]
I think we need to define what the following "things" are.

- What is the Verifiable Credential based on SD-JWTs?

I believe it is the JWT that contains the `_sd`s. It is not any of the combined formats. This means that the Verifiable Credential MAY NOT contain any disclosable claims, e.g., `name`. Would you agree @tlodderstedt, @Sakurann, Daniel?

The VC based on SD-JWT will have the media type `application/vc+sd-jwt`.

- What is the Verifiable Presentation based on SD-JWTs? It makes sense to define that since the HB JWT has some specific requirements. It also makes sense because protocol developers will need to refer to one term when they exchange presentations or verifiable presentations between issuer <-> holder <-> verifier.

Can we call the Combined Format for Issuance AND Presentation the Presentation based on SD-JWTs, and if there is HB, then it is a Verifiable Presentation? 

The VP based SD-JWT will have the media type `application/vp+sd-jwt` altough I'm not sure if this makes sense. Wouldn't it better to have `application/vp+vc+sd-jwt`? Any thoughts on that?

**Comment by awoie** [comment]
Also it is important to note that for OIDC4VP we use Verifiable Presentations in vp_token and we use Verifiable Credentials in OIDC4VCI in the credential response.

It probably has the implication that for OIDC4VP, we will put the VC based on SD-JWT into the credential response. What would be the credential format?

It probably also means that we would put the VP based on SD-JWT into the OIDC4VP vp_token.

**Comment by tlodderstedt** [comment]
We (IDunion) put the combined presentation (+hb jwt) in the vp_token. What else would you expect?

**Comment by awoie** [comment]
> We (IDunion) put the combined presentation (+hb jwt) in the vp_token. What else would you expect?

That makes sense, so the VP based on SD-JWT is the combined format for presentation including HB JWT.

Then, there is the question what would the OIDC4VCI credential response return? And what would be a format identifier? I know that this doesn't have to be answered in this spec but it helps with answering the terminology question.

**Comment by Sakurann** [comment]
Suggest we not overcomplicate things and say:
- what is returned in a VP Token in OID4VP is a combined Format for presentation with HB-JWT.
- what is returned in Credential Response in Credential Response in VCI is combined format for issuance.
- credential format identifier is 'vc+sd-jwt' for both.
- Terminology-wise, SD-JWT in the IETF spec is defined as an issuer signed JWS without disclosures. For this profile, the payload of SD-JWT, can be mapped back to a VCDM2.0
