### ISSUE TITLE
Why private claims are out of scope?

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/draft-terbu-sd-jwt-vc#108]
> JWTs (and SD-JWTs) can contain claims that are registered in "JSON Web Token Claims" registry as defined in [[RFC7519](https://vcstuff.github.io/draft-terbu-sd-jwt-vc/draft-terbu-sd-jwt-vc.html#RFC7519)], as well as public and private claims. Private claims are not relevant for this specification due to the openness of the three-party-model.

I do not understand this sentence. Because of the different use-cases, private claims are very relevant to the three-party model. 

(cc @tlodderstedt)

**Comment by awoie** [comment]
Can you give an example where this is relevant? With excluding private
claims we make sure all claims are uniquely identifiable across all parties
of the three-party-model.

**Comment by awoie** [comment]
We will also avoid name collisions this way.

**Comment by Sakurann** [comment]
Why are we worrying about name collisions? By prohibiting usage of private claims, We are limiting to the use-cases that need only public claims to express claims about the subject.

**Comment by paulbastian** [comment]
Aren't all the example in the spec right now using private claims instead of public claims? I don't see any problem with private claims

**Comment by awoie** [comment]
Ok, then we should say SHOULD use registered or public claims to facilitate
interop and avoid name collisions. Can you adjust your PR?

I really want folks just using private claims for use cases that are closed.

**Comment by awoie** [comment]
IMO, those examples should probably be fixed. Name collisions are a problem.

**Comment by paulbastian** [comment]
If we want to encourage public claims instead of private claims, then this should be reflected in some examples of the document

**Comment by tlodderstedt** [comment]
I agree with Kristina. I don't understand this constrained and miss a justification.

In my opinion, what we call private claim could also be a collision resistant claim defined by a community/sdo, that is just not registered in the IANA registry. Something like "<fqdn>.<claim>".

I suggest to revert to the previous text that allowed for private claims, too.

**Comment by awoie** [comment]
I thought that was included in the definition of a public claim. But I
double checked and you are right. We should fix that.

**Comment by awoie** [comment]
Closing this issue since we merged #109
