### ISSUE TITLE
don't use "Three-Party-Model"

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-terbu-sd-jwt-vc#111]
There are lots of things that could be described as a three-party model (including classic OAuth where this work is aspiring for adoption). The use of "Three-Party-Model" in this document strikes me as somewhat presumptuous and potentially misleading or confusing. Could we instead use "Issuer-Holder-Verifier Model"?

**Comment by peppelinux** [comment]
I agree, since there must be always a trusted third party in the model, like a trust anchor or its intermediate

**Comment by tlodderstedt** [comment]
I typically refer to this model as "decentralized identity" or "verifiable credentials applications/solutions/ecosystems", I would be fine with "digital credentials applications/solutions/ecosystems".

**Comment by bc-pi** [comment]
I'm suggesting only to replace the 5 or 6 usages of "Three-Party-Model" with "Issuer-Holder-Verifier Model".

**Comment by awoie** [comment]
That would work for me and I understand that Three-Party-Model is confusing since other architectures also involve 3 parties.

**Comment by tlodderstedt** [comment]
I'm ok with using "Issuer-Holder-Verifier Model".

**Comment by awoie** [comment]
It seems that this issue is ready for a PR.

**Comment by bc-pi** [comment]
> It seems that this issue is ready for a PR.

#138 is that PR
