### ISSUE TITLE
Same typ for JWT and SD-JWT?

### ISSUE THREAD

**Issue by tlodderstedt** [vcstuff/draft-terbu-sd-jwt-vc#129]
Should we consider to use the same `typ` header value for both variants, JWT and SD-JWT? I came across this when I was thinking about the OID4VC credential format profile for JWT-based VCs. A single `typ` would also result in a single format identifier in the presentation request, which might everyone's live easier. The only reason to distinguish would be that a dedicated format identifier for sd-jwt would allow the processor to directly decide whether selective disclosure is allowed in the presentation definition.

_Originally posted by @tlodderstedt in https://github.com/vcstuff/draft-terbu-sd-jwt-vc/pull/120#discussion_r1229300126_

**Comment by bc-pi** [comment]
Would it make sense to have the spec be only about SD-JWT VCs and treat the plain JWT VC as just a special case of an SD-JWT with no selectively disclosable claims? Then there wouldn't be variants and a single typ header value falls out naturally.

**Comment by awoie** [comment]
I guess after we merged PR #131 it seems we have decided to go with a single value for JWT VCs and SD-JWT VCs. Can we close this issue @tlodderstedt ?

**Comment by awoie** [comment]
As per editor's call from June 23rd, closing this since it was addressed by #131.
