### ISSUE TITLE
non-selectively disclosable registered JWT claims

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/draft-terbu-sd-jwt-vc#13]
currenlty, iss, iat, nbf, exp, cnf, type, status are listed as "non-selectively disclosable registered JWT claims".
What is the risk of selectively disclosing them? I do not have a strong opinion yet, but wanted to make sure we are making a conscious decision.

**Comment by danielfett** [comment]
I think the values that define the validity of the token should be non-SD so that a verifier always gets the "full picture". Similar for `iss`, which is critical for checking the token. 

For type, we have Issue #11 

Not sure about status, but I think it should also be non-SD.

**Comment by tlodderstedt** [comment]
I think every claim that is needed to evaluate the security/status of the credential must always be disclosed. For example, if the holder could omit the status, the verifier would never learn the credential was revoked by the issuer. I guess it is the issuer who should determine what must always be disclosed.

**Comment by awoie** [comment]
I would agree with @tlodderstedt

**Comment by awoie** [comment]
Closing this issue since nothing have to be changed. Current spec requires security-related claims to be always present in the SD-JWT.
