### ISSUE TITLE
"type" claim seems underspecified 

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-terbu-sd-jwt-vc#149]
Looking at -02 with kinda fresh eyes and the `type` claim seems like it needs something more. The places it shows up in the draft are linked and quoted below but basically say that the type is the type and gives one meaningless example (`{"type": "SomeType"}` is not helpful) and later an "e.g., IdentityCredential" that seems like it should be meaningful but isn't defined or explained anywhere that I could find. I realize this issue may seem pedantic or even silly but specs need to be specific about things like this or explain why they aren't specific and what the implications are. 

https://www.ietf.org/archive/id/draft-terbu-sd-jwt-vc-02.html#section-4.2.2.1

> This specification defines the JWT claim type. The type claim is used to express the type of the JSON object that is secured by the JWT. The type value MUST be a case-sensitive StringOrURI value.
> The following is a non-normative example of how type is used to express a type:
>`{"type": "SomeType"}`

https://www.ietf.org/archive/id/draft-terbu-sd-jwt-vc-02.html#section-4.2.2.2-3.6.1

>type
> REQUIRED. The type of the Verifiable Credential, e.g., IdentityCredential, as defined in [Section 4.2.2.1](https://www.ietf.org/archive/id/draft-terbu-sd-jwt-vc-02.html#type-claim).

**Comment by bc-pi** [comment]
Over [here](https://github.com/vcstuff/draft-terbu-sd-jwt-vc/issues/11#issuecomment-1562901265) Torsten suggests he sees it as "as identifier for a pre-defined bundle of claims associated with certain policies for enrollment and issuance" which may or may not be what it is intended. But is a lot more than the text in the draft says. And further suggests (to me anyway) that there's a gap between what is stated in the draft and what some think is defined.

**Comment by danielfett** [comment]
I totally agree that we need to improve this definition!

**Comment by Sakurann** [comment]
+1 to adding something like `"as identifier for a pre-defined bundle of claims associated with certain policies for enrollment and issuance"` sounds pretty accurate to me.

jfyi I think there is a conversation on renaming `type` claim in Issue #130.

**Comment by tlodderstedt** [comment]
here is a PR trying to improve the text #153

**Comment by awoie** [comment]
#153 was merged, closing this issue.
