### ISSUE TITLE
Support JSON-LD payload

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/draft-terbu-sd-jwt-vc#2]
would be good to normatively define both cases when payload is vanilla JSON and JSON-LD - IETF SD-JWT document only gives non-normative examples in 4a and 4b.

**Comment by Sakurann** [comment]
yes, agreed. this profile will focus only on JSON with a `typ` value `vc+sd-jwt`

**Comment by awoie** [comment]
Reopened this since I think we need to think through this again.

**Comment by Sakurann** [comment]
i disagre... especially if we will have one document how to sign vanilla JSON payload with SD-JWT and VC-JWT as proposed in issue #102, JSON-LD payload signed using SD-JWT VC being in the same draft will be very confusing. I agree that work is needed somewhere probably, but not in this draft.

**Comment by tlodderstedt** [comment]
I agree with Kristina. JWT and SD-JWT is more or less the same, that's the reason why (I think) we have consensus to a have single draft for it. JSON-LD is different (typing, claims names and semantics, processing) and deserves a dedicated spec.

**Comment by mprorock** [comment]
This should definitely focus on normal JSON/JWTs/SD-JWTs etc

**Comment by awoie** [comment]
Okay, then perhaps it make sense to also set the `cty` header accordingly. So that the JSON-LD version can be distinguished from the JSON version.

**Comment by tlodderstedt** [comment]
The typ should suffice.

**Comment by awoie** [comment]
Ok, I think there is unanimous agreement. Closing this issue.
