### ISSUE TITLE
Intro section might be too broad

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-terbu-sd-jwt-vc#34]
Feedback from @tlodderstedt :

> "However, JWTs do not support selective disclosure, i.e., the ability to disclose only a subset of the claims contained in the JWT. " is to broad - Suggest to frame it like this  "JWTs do not support selective disclosure in the issuer-holder-verifier model"

**Comment by tlodderstedt** [comment]
made a proposal in PR #52

**Comment by danielfett** [comment]
Fixed in PR #52.
