### ISSUE TITLE
JWT Issuer Metadata should support paths

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-terbu-sd-jwt-vc#36]
The rules for obtaining the issuer metadata needs to be extended to cope with paths as well. I suggest to use the text from https://www.rfc-editor.org/rfc/rfc8414.html#section-3.

**Comment by awoie** [comment]
The following example is already supported ...

```
"iss" = "https://www.rp.com"
--> www.rp.com/.well-known/jwt-issuer

"iss" = "https://www.rp.com/user/1234"
--> www.rp.com/user/1234/.well-known/jwt-issuer 
```

@tlodderstedt is this what you had in mind, or is there anything missing? In that case, we could add an example that makes it more visible that this use case is supported.

**Comment by tlodderstedt** [comment]
https://example.com/user/1234/.well-known/jwt-issuer needs to be https://example.com/.well-known/user/1234/jwt-issuer 

have a look at https://www.rfc-editor.org/rfc/rfc8414.html#section-3

**Comment by awoie** [comment]
Ok, makes sense. Will create a PR to fix that.
