### ISSUE TITLE
analyze and clarify the diff with vc-jwt?

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/draft-terbu-sd-jwt-vc#37]
The usage of a Holder Binding JWT as defined in [IETF.SD-JWT] might be a different mechanism from Verifiable Presentation as defined in [W3C.VCDM2.0]/[vc-jwt], while achieving the same goal.

maybe not needed. not sure if this will bring clarify or more confusion

**Comment by awoie** [comment]
The current text of VC SD-JWT has nothing to do with VC-JWT as per W3C.

**Comment by Sakurann** [comment]
Ok. Than we are not dependent on VC-JWT for nbf too (issue #12)
