### ISSUE TITLE
guidance around the `sub` claim.

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/draft-terbu-sd-jwt-vc#5]
”sub” Claim MAY be supported by the Issuer. There is no requirement for a binding to exist between `sub` and `cnf` claims.

**Comment by awoie** [comment]
That makes sense.

**Comment by awoie** [comment]
So, you are saying we need to define something like: if there is a `sub` and a `cnf`, then the `cnf` should authenticate the `sub`?

**Comment by Sakurann** [comment]
I am saying that 
1. `cnf` is used for cryptographic holder binding.
2. `sub` is used as the user's identifier within the Issuer's namespace.
3. if Issuer chooses to establish a relationship between a `cnf` and a `sub` (such as sub is a JWK thumbprint of a JWK in a cnf claim), but it is not necessary (not sure this even needs to be mentioned in the spec, if so, probably implementation considerations)

**Comment by awoie** [comment]
fixed by PR #14
