### ISSUE TITLE
Describe HB-JWT for VPs

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-terbu-sd-jwt-vc#58]
The SD-JWT spec does not define how to construct the HB-JWT. It would be nice if the HB-JWT could bind the signature to the transaction, i.e., the rest of the SD-JWT combined format for presentation. I'd suggest, we define the following payload for the HB-JWT:

```
{
  "nonce": "123456",
  "aud": "https://rp.com",
  "iat": 12345,
  "exp": 123456,
  "_tx_hash": sha256(<sd-jwt>~<d1>~...~<dn>)
}
```

**Comment by awoie** [comment]
Because the HB-JWT does not sign any other disclosures, any non-repudiation attacks are not possible.

**Comment by danielfett** [comment]
Note that also SD-JWT will be more specific on the HB JWT: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/262
