### ISSUE TITLE
Introduction description on Status Provider

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-terbu-sd-jwt-vc#93]
The spec says:

> To support revocation of Verifiable Credentials, an optional fourth party can be involved, a Status Provider, who delivers revocation information to Verifiers. (The Verifier can also serve as the Status Provider.)

I think this is not optimal, as
1. revocation is just an example of status
2. Status Providers do not need to be a fourth party
3. Verifiers are usually not the status provider but the issuer?

I would suggest:
"To make status information of a Verifiable Credential after its issuance available, an optional Status Provider can provide status data, e.g. revocation. The role of the Status Provider can be assigned to the Issuer or an optional fourth party."

**Comment by awoie** [comment]
@paulbastian Since we merge https://github.com/vcstuff/draft-terbu-sd-jwt-vc/pull/122, can we close this issue?

**Comment by paulbastian** [comment]
Yes

**Comment by awoie** [comment]
Closing since #122 got merged.
