### ISSUE TITLE
Introduction description on Rationale

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-terbu-sd-jwt-vc#94]
The spec says:

> However, JWT-based credentials do not support selective disclosure, i.e., the ability for a Holder to disclose only a subset of the claims contained in the JWT, which is a requirement to implement the three-party-model efficiently.

In my opinion this is not correct, because the text basically says: "JWT-based credentials do not support selective disclosure [...] which is a requirement to implement the three-party-model efficiently". Imo the need for SD-JWT comes from the shift from IdP to three-party-model.

My proposal:
"While JWT-based credentials enable selective disclosure, i.e., the ability for a holder to disclose only a subset of the contained claims, in an Identity Provider ecosystem by issuing new JWTs to the Verifier for every presentation, this approach does not work in the three-party-model."

**Comment by tlodderstedt** [comment]
+1

**Comment by awoie** [comment]
@paulbastian do you want to create the PR? Or should I create the PR?

**Comment by paulbastian** [comment]
I can do, just wanted to make sure its not for waste. Issue is less effort ;P
