### ISSUE TITLE
Are we missing a chapter on creation?

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-terbu-sd-jwt-vc#98]
While RFC7519 on JWTs has a chapter on Creation of JWTs, the SD-JWT and this spec jump right to Examples on continue with guideline for presentation/verification. Do you see any need for such a Creation chapter/section?

**Comment by danielfett** [comment]
How SD-JWTs are created is well defined in the SD-JWT spec. There is no need to have a section on creating SD-jWTs here.
